title: Shixing Yu
description: This is my homepage
show_downloads: true
google_analytics:
theme: jekyll-theme-cayman
author:
  name: ## 作者名
  intro_line1:  "Hello ,I'm Larry Page in Google."    ## 网站底部的个人介绍
  intro_line2:  "This is my blog,believe it or not."  
